### ISSUE TITLE
galiq griffin sayb lina brew

### ISSUE THREAD

**Issue by OGSett** [su-omb/my_tools_installer#10]
galiq griffin sayb lina brew
galiq griffin sayb lina brew
galiq griffin sayb lina brew
galiq griffin sayb lina brew
galiq griffin sayb lina brew

**Comment by ombhd** [comment]
After doing some investigation, it appeared that the school infra was not totally configured yet, so now, the script is working well.

**Comment by OGSett** [comment]
thaank u
