### ISSUE TITLE
build error when curl fails due to ssl problem

### ISSUE THREAD

**Issue by ombhd** [su-omb/my_tools_installer#2]
### problem:
if ssl certificate is expired the brew fail to install packages
### suggested solution:
integrate the second solution of this question in the script when detecting ssl problem:
[Homebrew Cask download failure. SSL certificate problem: certificate has expired](https://apple.stackexchange.com/questions/393481/homebrew-cask-download-failure-ssl-certificate-problem-certificate-has-expired)

**Comment by haitkadir** [comment]
here is another good and saving time solution

https://stackoverflow.com/questions/57629010/linuxbrew-curl-certificate-issue
